name: "ps-jfrog-gitbub-oidc-npm-publish"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
  contents: read

jobs:
  build:
     runs-on: ubuntu-24.04
     env:
      OIDC_AUDIENCE: 'ps-jfrog-oidc'
      OIDC_PROVIDER: 'ps-jfrog-labs'
      PLATFORM_REPO: 'blr-npm-stage-virtual'
     steps:
       - name: Checkout
         uses: actions/checkout@v3
              
       - name: Setup Node npm
         uses: actions/setup-node@v3
   
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         env:  
           JF_URL: ${{ secrets.JF_URL }}
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           oidc-audience: ${{ env.OIDC_AUDIENCE }}

       - name: Run Audit scan for the git workspace
         run: jf audit .

       - name: Set CLI Config
         run: jf npm-config --global=true --repo-resolve=$PLATFORM_REPO --repo-deploy=$PLATFORM_REPO
           
       - name: Install Dependencies
         run: jf npm install --build-name="ps-jfrog-gitbub-oidc-npm-publish" --build-number=${{ github.run_number }}
         
       - name: Publish
         run: jf npm publish --build-name="ps-jfrog-gitbub-oidc-npm-publish" --build-number=${{ github.run_number }}
         
       - name: Publish Build info With JFrog CLI
         run: |
          # Collect environment variables for the build
          jf rt bce ps-jfrog-gitbub-oidc-npm-publish ${{ github.run_number }}
          # Collect VCS details from git and add them to the build
          jf rt build-add-git ps-jfrog-gitbub-oidc-npm-publish ${{ github.run_number }}
          # Publish build info
          jf rt bp ps-jfrog-gitbub-oidc-npm-publish ${{ github.run_number }}
